CI: azure
c_compiler: vs2017
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2017
extend_keys:
- pin_run_as_build
- ignore_version
- ignore_build_only_deps
- extend_keys
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
numpy: '1.16'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: 3.8.* *_cpython
r_base: '3.4'
target_platform: win-64
vc: '14'
