CI: azure
c_compiler: '*'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: '*'
extend_keys:
- ignore_version
- ignore_build_only_deps
- extend_keys
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
lua: '5'
numpy: '1.16'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '2.7'
python_abi_tag: cp38
python_impl: '*'
python_impl_version: '3.8'
python_implementation: cpython
python_version: '3.8'
r_base: '3.4'
target_platform: win-64
vc: '*'
zip_keys:
- - python
  - python_impl
- - python_abi_tag
  - python_version
  - python_impl_version
  - python_implementation
